
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommylee
 */
public class basketballmainframe extends javax.swing.JFrame {
     DBConnection db;
Map<Integer,String> listSeason;
ComboBoxModel selectionmodel;
ComboBoxModel teamaselectionmodel;
ComboBoxModel teamaselectionmodelx;
DefaultListModel dmsquada;
DefaultListModel dmsquadb;
Map<Integer,String> tempx;
int seasonx;
//This is one instance of the  map you want to store in the above list.
    /**
     * Creates new form basketballmainframe
     * @throws java.sql.SQLException
     */
    public basketballmainframe() throws SQLException {
        db=new DBConnection();
        
        listSeason=db.selection();
      
         Object[] values = listSeason.values().toArray();
     selectionmodel= new DefaultComboBoxModel(values);
 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        seasonselect = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        editSeason = new javax.swing.JButton();
        deleteSeason = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeambPlayerList = new javax.swing.JList<>();
        teama = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TeamaPlayerList = new javax.swing.JList<>();
        teamb = new javax.swing.JComboBox<>();
        startButton = new javax.swing.JButton();
        warnlabel = new javax.swing.JLabel();
        DatabaseFrameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basketball.png"))); // NOI18N
        jLabel1.setSize(new java.awt.Dimension(16, 16));

        seasonselect.setModel(selectionmodel);
        seasonselect.setToolTipText("");
        if(!listSeason.isEmpty())
        seasonselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seasonselectActionPerformed(evt);
            }
        });
        try{
            seasonselect.setSelectedIndex(0);
        }catch(Exception e){
            seasonselect.removeAll();
        }

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("賽季：");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("新建");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editSeason.setBackground(new java.awt.Color(153, 153, 153));
        editSeason.setForeground(new java.awt.Color(51, 51, 51));
        editSeason.setText("編輯");
        editSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSeasonActionPerformed(evt);
            }
        });

        deleteSeason.setBackground(new java.awt.Color(153, 153, 153));
        deleteSeason.setForeground(new java.awt.Color(51, 51, 51));
        deleteSeason.setText("刪除");
        deleteSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSeasonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(TeambPlayerList);

        teama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamaActionPerformed(evt);
            }
        });
        try{
            teama.setSelectedIndex(0);
        }catch(Exception e){
            teama.removeAll();
        }

        jScrollPane2.setViewportView(TeamaPlayerList);

        teamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teambActionPerformed(evt);
            }
        });
        try{
            teamb.setSelectedIndex(1);
        }catch(Exception e){
            teamb.removeAll();
        }

        startButton.setBackground(new java.awt.Color(153, 153, 153));
        startButton.setForeground(new java.awt.Color(0, 51, 51));
        startButton.setText("開始");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        warnlabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        DatabaseFrameButton.setText("球員數據");
        DatabaseFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseFrameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seasonselect, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSeason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteSeason)
                .addGap(0, 32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DatabaseFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(warnlabel)
                                .addGap(282, 282, 282))
                            .addComponent(startButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teama, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(teamb, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seasonselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(editSeason)
                    .addComponent(deleteSeason))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatabaseFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warnlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      CreateFrame create;
         try {
             create = new CreateFrame();
        create.setSize(650,500);
          create.setVisible(true);
     
      create.setTitle("新建隊伍");
         } catch (SQLException ex) {
             Logger.getLogger(basketballmainframe.class.getName()).log(Level.SEVERE, null, ex);
         }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSeasonActionPerformed
         try {
                System.out.println(seasonselect.getSelectedIndex());
             int seasonId=db.getSeasonIDbyname(seasonselect.getSelectedItem());
             // TODO add your handling code here:
             listSeason.remove(seasonselect.getSelectedIndex());
             Object[] values = listSeason.values().toArray();
             selectionmodel= new DefaultComboBoxModel(values);
             seasonselect.setModel(selectionmodel);
          
             db.deleteSeason(seasonId);
             basketballmainframe bf=new basketballmainframe();
             bf.setVisible(true);
             this.dispose();
         } catch (SQLException ex) {
             Logger.getLogger(basketballmainframe.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_deleteSeasonActionPerformed

    private void editSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSeasonActionPerformed
        // TODO add your handling code here:
        int seasonId=db.getSeasonIDbyname(seasonselect.getSelectedItem());
        ModifyFrame mod=new ModifyFrame(seasonId);
        mod.setVisible(true);
    }//GEN-LAST:event_editSeasonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        int seasonId=db.getSeasonIDbyname(seasonselect.getSelectedItem());
        int teamAId=db.getteamIDbyname(teama.getSelectedItem(),seasonId);
        int teamBId=db.getteamIDbyname(teamb.getSelectedItem(),seasonId);
        if(teamAId!=teamBId){
            
        Game game=new Game(teamAId,teamBId,seasonx);
        this.setVisible(false);
        game.setVisible(true);
        
        }
        warnlabel.setText("隊伍不能相同！");
    }//GEN-LAST:event_startButtonActionPerformed

    private void teambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teambActionPerformed
        // TODO add your handling code here:
              Object[] values = tempx.keySet().toArray();
        
        dmsquadb=new DefaultListModel();
        dmsquadb.clear();
        int seasonid =db.getSeasonIDbyname(seasonselect.getSelectedItem());
        List<PlayerStat> listPlayer=db.getPlayer(teamb.getSelectedItem(),seasonid);
        System.out.print("Num of players:"+listPlayer.size());
        for(PlayerStat Player:listPlayer)
        {
             dmsquadb.addElement(Player.getPlayerNum()+"  "+Player.getPlayerName());
        }
        TeambPlayerList.setModel(dmsquadb);
    }//GEN-LAST:event_teambActionPerformed

    private void seasonselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seasonselectActionPerformed
        // TODO add your handling code here:
        
      tempx= db.getTeamList(db.getSeasonIDbyname(seasonselect.getSelectedItem()));
        Object[] values = tempx.values().toArray();
        try{
            startButton.setVisible(true);
            warnlabel.setText("");
     teamaselectionmodel= new DefaultComboBoxModel(values);
     teama.setModel(teamaselectionmodel);
          teamaselectionmodelx= new DefaultComboBoxModel(values);
     teamb.setModel(teamaselectionmodelx);
     seasonx =db.getSeasonIDbyname(seasonselect.getSelectedItem());
     teama.setSelectedIndex(0);

     
     teamb.setSelectedIndex(1);
        }
        catch(Exception e){
           warnlabel.setText("隊伍不足！"); 
           startButton.setVisible(false);
        }
    }//GEN-LAST:event_seasonselectActionPerformed

    private void teamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamaActionPerformed
        // TODO add your handling code here:
        Object[] values = tempx.keySet().toArray();
        
        dmsquada=new DefaultListModel();
        dmsquada.clear();
        int seasonid=db.getSeasonIDbyname(seasonselect.getSelectedItem());
        List<PlayerStat> listPlayer=db.getPlayer(teama.getSelectedItem(),seasonid);
        for(PlayerStat Player:listPlayer)
        {
             dmsquada.addElement(Player.getPlayerNum()+"  "+Player.getPlayerName());
        }
        TeamaPlayerList.setModel(dmsquada);
    }//GEN-LAST:event_teamaActionPerformed

    private void DatabaseFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseFrameButtonActionPerformed
        // TODO add your handling code here:
        DatabaseFrame fr=new DatabaseFrame();
                this.setVisible(false);
        fr.setVisible(true);
    }//GEN-LAST:event_DatabaseFrameButtonActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basketballmainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basketballmainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basketballmainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basketballmainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               basketballmainframe mainframe;
                try { 
                   mainframe = new basketballmainframe();
   
                mainframe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               mainframe.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(basketballmainframe.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DatabaseFrameButton;
    private javax.swing.JList<String> TeamaPlayerList;
    private javax.swing.JList<String> TeambPlayerList;
    private javax.swing.JButton deleteSeason;
    private javax.swing.JButton editSeason;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> seasonselect;
    private javax.swing.JButton startButton;
    private javax.swing.JComboBox<String> teama;
    private javax.swing.JComboBox<String> teamb;
    private javax.swing.JLabel warnlabel;
    // End of variables declaration//GEN-END:variables
}
